# Site settings
title: Beaker Browser
email: pfrazee@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beakerbrowser.com" # the base hostname & protocol for your site
twitter_username: pfrazee
github_username:  pfrazee

# Build settings
markdown: kramdown
theme: minima
include: [".well-known"]
exclude: ["node_modules"]
keep_files: [".dat"]
gems:
 - jekyll-redirect-from
 - octopress-minify-html

# Sass
sass:
  style: :compressed
  sass_dir: css

minify_html: false

# Site data
collections:
  releases:
    output: true
  docs:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  -
    scope:
      path: ""
      type: "releases"
    values:
      layout: "release"
